### ISSUE TITLE
fail to read responses from backend

### ISSUE THREAD

**Issue by burnout87** [cdcihub/ddaclient#6]
Following issue on sentry:

https://cdci.sentry.io/issues/5569090703/?project=1467382&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=24h&stream_index=2&utc=true

**Comment by volodymyrss** [comment]
I added more log in 365194a59046e564ed5e88ff212d7b723f3e6b27 . I am very much inclined to think this is a an incident on the backend/infrastructure so it must have recovered. But we need to check to be sure.
